services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: lazyvolt-ha
    volumes:
      - ./ha-config:/config
      - ./custom_components:/config/custom_components
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    extra_hosts:
      # Reach the Cloud at http://host.docker.internal:80
      # Also enables reaching local network devices (Peblar, P1 meter) via host routing
      - "host.docker.internal:host-gateway"
